dados = input("Informe seu nome: ")
print(dados.upper())
print(dados.lower())
print(dados.title())
print(dados.replace("a", "@"))
print(dados.count(dados))
print(len(dados))
print(dados.find("a"))
print(dados[6::-1])