CREATE SCHEMA IF NOT EXISTS `PROJETO_AERONAVE`;
USE `PROJETO_AERONAVE`;

CREATE TABLE IF NOT EXISTS `TB_USERS`(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(128) NOT NULL,
    STATUS INT NOT NULL
);

CREATE TABLE IF NOT EXISTS `TB_AERONAVES`(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    MODELO VARCHAR(100) NOT NULL,
    ANO INT NOT NULL,
    COR VARCHAR(30),
    TIPO INT
);

INSERT INTO `TB_USERS` (NOME, EMAIL, SENHA, STATUS) VALUES ('salu', 'salubcosta@gmail.com', '123', 1);
SELECT * FROM `TB_USERS`;
SELECT * FROM `TB_AERONAVES`;